export const VALIDATION_LIMITS = {
  NAME_MIN: 1,
  NAME_MAX: 100,
  PASSWORD_MIN: 6,
  CUSTOM_ID_MAX: 96,
  TOKEN_MIN: 1,
  DESCRIPTION_MAX: 500,
  TAG_NAME_MAX: 50,
} as const;

export const BATCH_LIMITS = {
  INVENTORIES_MAX: 200,
  ITEMS_MAX: 200,
  USERS_MAX: 200,
  TAGS_MAX: 50,
  POPULAR_ITEMS_MAX: 50,
  RECENT_ITEMS_MAX: 50,
} as const;

export const PAGINATION = {
  MIN_PAGE: 1,
  MIN_PER_PAGE: 1,
  MAX_PER_PAGE: 100,
  DEFAULT_PER_PAGE: 20,
} as const;

export const SEARCH = {
  MIN_LENGTH: 3,
  MAX_LENGTH: 100,
  AUTOCOMPLETE_MIN: 1,
  AUTOCOMPLETE_MAX_LIMIT: 25,
  AUTOCOMPLETE_DEFAULT_LIMIT: 10,
} as const;
